# Generated by Django 6.0.5 on 2026-05-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_groupprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupprofile',
            options={'permissions': [('access_admin_panel', 'Can access admin panel')]},
        ),
    ]
